### PR TITLE
Refactor imputer

### PR DESCRIPTION
**Pull request by luofanghao**
Hi I refactored the Imputer class. Now the usage supports:

1. analysis() will run baseline method, and also missing pattern analysis (this is to be done)
2. fit() & transform() for the imputation method that needs to learn from given dataset (now only: greedySearch)
3. complete() for the imputation method that does not to learn anything from given dataset. (now support: iteratively regress, will support other imputation method from "fancyimpute")

Do you think this is reasonable? @kyao @rpedsel

### CODE REVIEW

**Review by kyao — COMMENTED** [review]
I think it would be better to follow the sklearn API of fit() and transform(). 

We should not have the complete() method. If a particular imputation approach does not require training data, then the fit() method can be implemented as no-op. Also, complete() takes an additional parameter. If a transformation requires extra parameters, they should be defined as part of the __init__() method.

Also, if having too many parameters to init is confusing, perhaps we should split the Imputer into multiple classes.

The analysis() method seems to be for our internal use. Having this method is fine. We will just not expose it to the TA2 folks to avoid confusing them.

**Comment by kyao** [comment]
Also, should we be keeping regression coefficients for iterative regress? The training dataset is typically much larger. We learn the coefficients from the training dataset, then we apply to the testing dataset.

The question is which coefficients to keep? Keep the coefficients from the last round of iteration?

**Comment by luofanghao** [comment]
@kyao what about now? All imputation methods will have same procedure: fit() and transform(). Also hide analysis().

And yes I think keeping the coefficients from last round of iteration makes sense to me.

**Comment by kyao** [comment]
Is there a reason to put the 'strategy' parameter in the fit() method, instead of defining the strategy as part of object instantiation __ init__()? Defining it within the init method seems more consistent with sklearn.

**Comment by luofanghao** [comment]
@kyao now the usage is like:

```python
# method: regression
imputer = Imputation(model=clf, scorer=scorer, strategy="iteratively_regre")
imputer.fit(data)
data_clean = imputer.transform(data, label)

# method: greedy search
# imputer = Imputation(model=clf, scorer=scorer, strategy="greedy")
# imputer.fit(data, label)
# data_clean = imputer.transform(data)
# print imputer.best_imputation
```

is this good?

**Comment by kyao** [comment]
Looks good! Please merge into master.

**Pull request merged**
